kakao:
  rest-api-key: 571571d2a3b3c545b0d5bc6ce988f0ed
  redirect-uri: http://localhost:8080/member/kakao

#spring:
#  datasource:
#    url: ${DB_URL}
#    username: ${DB_USERNAME} 
#    password: ${DB_PASSWORD}
#    driver-class-name: org.postgresql.Driver