spring:
  application:
    name: keezna
  config:
    import:
    - optional:classpath:application-secret.yaml

server:
  port: 19090 
  tomcat:
    accesslog:
      enabled: true
      pattern: '%h %l %u %t "%r" %s %b'
      directory: c:/Temp/logs/tomcat
      prefix: access_log



  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        highlight_sql: true

  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB

logging:
  level:
    org:
      hibernate:
        SQL: INFO
        orm:
          jdbc:
            bind: TRACE
      springframework:
        security:
          web: trace
